version: 2

builds:
  - id: hsla
    binary: hlsa
    main: ./cmd/hlsa/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: "tar.gz"
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^feat:"
      order: 0
    - title: Bug Fixes
      regexp: "^fix:"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: donaldgifford
    name: hlsa
  draft: false
  prerelease: auto
  mode: prepend
  header: |
    ## Release {{ .Tag }} ({{ .Date }})

  footer: |
    ---
    **Full Changelog**: https://github.com/donaldgifford/hlsa/compare/{{ .PreviousTag }}...{{ .Tag }}

snapshot:
  version_template: "{{ .Tag }}-dev"
